<script setup>
import { ref, onMounted } from "vue";
import gsap from "gsap";

const svgEl = ref(null);
const lineSpacing = 2;
const viewBoxHeight = 63.5;
const linesCount = Math.ceil(viewBoxHeight / lineSpacing);

// expose the play function so parent can trigger it after transitions
function animate() {
  const tl = gsap.timeline();

  // Entry sweep: move the scan bar + mask down in sync
  tl.to(
    "#scan-bar",
    {
      y: viewBoxHeight,
      duration: 1.2,
      ease: "power2.inOut",
    },
    0,
  );

  tl.to(
    "#scan-reveal",
    {
      y: viewBoxHeight,
      duration: 1.2,
      ease: "power2.inOut",
    },
    0,
  );

  // Fade the scan bar away once reveal is done
  tl.to(
    "#scan-bar",
    {
      opacity: 0,
      duration: 0.3,
      ease: "power1.inOut",
    },
    "+=0.05",
  );

  // Ambient hologram effects (run after reveal)
  tl.add(() => {
    // subtle portrait flicker (randomized repeatDelay)
    gsap.to("#portrait-group", {
      opacity: 0.9,
      duration: 0.08,
      repeat: -1,
      yoyo: true,
      repeatDelay: gsap.utils.random(1.5, 3, true),
      ease: "power1.inOut",
    });

    // scanlines drift: move each rect downward and wrap using modifiers for seamless loop
    gsap.to("#scanlines > rect", {
      duration: 0.8,
      y: `+=${lineSpacing}`,
      repeat: -1,
      ease: "none",
      modifiers: {
        y: gsap.utils.unitize((y) => {
          // keep y between 0 and lineSpacing * linesCount so it wraps visually
          const num = parseFloat(y);
          const max = lineSpacing * linesCount;
          return String(((num % max) + max) % max);
        }),
      },
    });
  }, ">-0.05"); // start almost immediately after scan bar fade

  return tl;
}

defineExpose({ animate });

onMounted(() => {
  // ensure mask and bar are positioned above at start
  gsap.set("#scan-bar", { y: -viewBoxHeight });
  gsap.set("#scan-reveal", { y: -viewBoxHeight });
});
</script>

<template>
  <div class="hologram-stage">
    <svg
      ref="svgEl"
      width="1200"
      height="240"
      viewBox="0 0 317.5 63.5"
      xmlns="http://www.w3.org/2000/svg"
      role="img"
      aria-label="Hologram portrait"
    >
      <defs>
        <!-- Gradient for scan bar -->
        <linearGradient id="scanGradient" x1="0" y1="0" x2="0" y2="1">
          <stop
            offset="0%"
            stop-color="var(--laser-color, #00ff7f)"
            stop-opacity="0"
          />
          <stop
            offset="50%"
            stop-color="var(--laser-color, #00ff7f)"
            stop-opacity="0.6"
          />
          <stop
            offset="100%"
            stop-color="var(--laser-color, #00ff7f)"
            stop-opacity="0"
          />
        </linearGradient>

        <!-- Mask used to reveal the portrait under the scan -->
        <mask id="scanMask">
          <!-- white region reveals, start positioned above viewBox -->
          <rect
            id="scan-reveal"
            x="0"
            y="-63.5"
            width="317.5"
            height="63.5"
            fill="white"
          />
        </mask>
      </defs>

      <!-- Portrait group (replace the placeholder with your <image> or traced svg group) -->
      <g id="portrait-group" mask="url(#scanMask)">
        <!-- Example placeholder: replace with your image or vector portrait -->
        <rect x="120" y="10" width="80" height="40" rx="6" fill="white" />
      </g>

      <!-- Glowing scan bar that sweeps down -->
      <rect
        id="scan-bar"
        x="0"
        y="-4"
        width="317.5"
        height="4"
        fill="url(#scanGradient)"
        opacity="0.9"
      />

      <!-- Scanlines: generated by v-for -->
      <g id="scanlines" opacity="4" fill="var(--laser-color, #00ff7f)">
        <rect
          v-for="i in linesCount"
          :key="i"
          x="0"
          :y="i * lineSpacing"
          :width="317.5"
          :height="1"
        />
      </g>
    </svg>
  </div>
</template>

<style scoped>
.hologram-stage {
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
  width: 100%;
  border-radius: 12px;
  border: 1px solid var(--laser-color, #00ff7f);
}

/* make scanlines subtle in light mode; color via CSS variable */
svg {
  max-width: 100%;
  height: auto;
  display: block;
}

/* tune scanline visibility */
#scanlines rect {
  fill: var(--laser-color, #00ff7f);
  opacity: 0.15;
}
</style>
