name: Security Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggers

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run security audit
        run: bun audit || true

      - name: Check for vulnerabilities in lock file
        run: |
          # Run audit and capture output
          AUDIT_OUTPUT=$(bun audit --json 2>&1 || true)
          
          # Check if there are high or critical vulnerabilities
          if echo "$AUDIT_OUTPUT" | grep -q '"severity":"high"\|"severity":"critical"'; then
            echo "⚠️ High or critical vulnerabilities found!"
            echo "$AUDIT_OUTPUT"
            exit 1
          else
            echo "✅ No high or critical vulnerabilities found"
          fi

      - name: Upload audit results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-audit-report
          path: |
            bun-audit.log
          retention-days: 30

  # Check for outdated dependencies
  outdated-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check for outdated dependencies
        run: |
          echo "📦 Checking for outdated dependencies..."
          bun outdated || true
          
      - name: Comment on PR if outdated major versions exist
        if: github.event_name == 'pull_request'
        run: |
          OUTDATED=$(bun outdated --json 2>&1 || echo "[]")
          if [ "$OUTDATED" != "[]" ]; then
            echo "ℹ️ Some dependencies have newer versions available. Review manually for breaking changes."
          fi
